name: app
description: A containerized Dart environment.
version: 1.0.0
# repository: https://github.com/DramatikMan/dart-enviornment

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.1
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
